global:
  scrape_interval: 15s
scrape_configs:
  - job_name: "globalticket-events"
    static_configs:
      - targets: ["events-service:8080"]
  - job_name: "globalticket-tickets"
    static_configs:
      - targets: ["tickets-service:8080"]
